KEEPALIVED_COMMAND_LINE_ARGUMENTS: --log-detail --dump-conf

KEEPALIVED_INTERFACE: eth0
KEEPALIVED_PASSWORD: d0cker
KEEPALIVED_STATE: BACKUP

# For electing MASTER, highest priority wins.
# to be MASTER, make 50 more than other machines
KEEPALIVED_PRIORITY: 150

KEEPALIVED_UNICAST_PEERS:
  - 192.168.1.10

KEEPALIVED_VIRTUAL_IPS:
  - 192.168.99.200

KEEPALIVED_NOTIFY: /container/service/keepalived/assets/notify.sh
